arthenica/ffmpeg-kit

android/README.md

Make the examples more explicit
Documentation
Made some rush explication here https://github.com/tanersener/ffmpeg-kit/issues/34#issuecomment-833809940

Explicit SAF read & write instructions

---

.github/ISSUE_TEMPLATE/bug_report.md

Remove Duplication Option for Expected Behaviour
- Documentation / Bug Reporting Template

Remove Duplicate Expected Behaviour Option

---

README.md
android/ffmpeg-kit-android-lib/src/main/java/com/arthenica/ffmpegkit/FFmpegKit.java
android/ffmpeg-kit-android-lib/src/main/java/com/arthenica/ffmpegkit/FFmpegKitConfig.java
android/ffmpeg-kit-android-lib/src/main/java/com/arthenica/ffmpegkit/FFprobeKit.java
apple/src/FFmpegKit.h
apple/src/FFmpegKitConfig.h
apple/src/FFprobeKit.h
flutter/flutter/README.md
flutter/flutter/lib/ffmpeg_kit.dart
flutter/flutter/lib/ffmpeg_kit_config.dart
flutter/flutter/lib/ffprobe_kit.dart
react-native/README.md
react-native/src/index.js

Improve the documentation and give more details about async execute methods and supported Android/iOS versions.

Improve documentation

---

.github/workflows/nightly-builds-android.yml
.github/workflows/nightly-builds-apple.yml
android/ffmpeg-kit-android-lib/build.gradle
tools/release/android/build.gradle
tools/release/android/build.lts.gradle

Builds Android releases with NDK r22b, fixes #292
- Bug fix
Manually tested.

merge the bugfix for issue 292

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/ios-build-scripts.yml
.github/workflows/macos-build-scripts.yml
.github/workflows/stale.yml
.github/workflows/tvos-build-scripts.yml
README.md
apple/src/FFprobeKit.h
docs/index.md

merge documentation changes to main

---

.github/workflows/android-build-scripts.yml
.github/workflows/ios-build-scripts.yml
.github/workflows/macos-build-scripts.yml
.github/workflows/tvos-build-scripts.yml
android/README.md

Doc update to use the latest version in `Android`.

Android 4.5.1-1 doc update

---

.github/workflows/android-build-scripts.yml
scripts/android/ffmpeg.sh

fix disabling ffmpeg-kit protocols in android build scripts, fixes #395

---

README.md

merge documentation changes

---

.github/workflows/android-build-scripts.yml
.github/workflows/ios-build-scripts.yml
.github/workflows/macos-build-scripts.yml
.github/workflows/tvos-build-scripts.yml

Enables pr builds for the development branch
- CI

enable pr builds for development branch

---

android/README.md
android/ffmpeg-kit-android-lib/src/main/cpp/fftools_ffmpeg.c
apple/src/fftools_ffmpeg.c
linux/src/fftools_ffmpeg.c
scripts/function-android.sh

Fixes [804](https://github.com/arthenica/ffmpeg-kit/issues/804), [809](https://github.com/arthenica/ffmpeg-kit/issues/809) and patches native 6.0 releases.
- Patch
Tested by the test applications in the ffmpeg-kit-test repo

patch native v6.0 releases

---

flutter/flutter/CHANGELOG.md
flutter/flutter/README.md
flutter/flutter/android/build.gradle
flutter/flutter/ios/ffmpeg_kit_flutter.podspec
flutter/flutter/lib/src/ffmpeg_kit_factory.dart
flutter/flutter/macos/ffmpeg_kit_flutter.podspec
flutter/flutter/pubspec.yaml

merge flutter v6.0.2 to main
- Patch
Tested by the test applications in the ffmpeg-kit-test repo

merge flutter v6.0.2 to main

---

README.md
docs/index.md

fix the release table

---

flutter/flutter/README.md

should !=
but there use ==
How are these changes verified? Please provide test instructions.
Also list any relevant details about your test configuration.

fix(doc): Get media information for a file/url example

---

flutter/flutter/README.md

Reverts arthenica/ffmpeg-kit#824

Revert "fix(doc): Get media information for a file/url example"

---

.github/workflows/periodic-builds-android.yml
.github/workflows/periodic-builds-apple.yml

fix github action errors
- Bug fix

fix github action errors

---

.github/workflows/stale.yml

update stale action rules
- New feature

update stale action rules

---

flutter/flutter/CHANGELOG.md
flutter/flutter/README.md
flutter/flutter/analysis_options.yaml
flutter/flutter/android/build.gradle
flutter/flutter/ios/ffmpeg_kit_flutter.podspec
flutter/flutter/lib/abstract_session.dart
flutter/flutter/lib/src/ffmpeg_kit_factory.dart
flutter/flutter/macos/ffmpeg_kit_flutter.podspec
flutter/flutter/pubspec.yaml

merge flutter v6.0.3 to main
- Patch
Tested by the test applications in the ffmpeg-kit-test repo

merge flutter v6.0.3 to main

---

.github/workflows/periodic-builds-android.yml
docs/index.md

fix periodic android github actions
- Bug fix

fix periodic android github actions

---

.github/workflows/android-build-scripts.yml
.github/workflows/ios-build-scripts.yml
.github/workflows/linux-build-scripts.yml
.github/workflows/macos-build-scripts.yml
.github/workflows/periodic-builds-android.yml
.github/workflows/periodic-builds-apple.yml
.github/workflows/tvos-build-scripts.yml
scripts/apple/libvorbis.sh
scripts/function-apple.sh
scripts/function-ios.sh
scripts/function-macos.sh
scripts/function-tvos.sh

fix rubberband x86-64 builds on xcode 15.x
- Bug fix

fix rubberband x86-64 builds on xcode 15.x

---

.github/workflows/android-build-scripts.yml
.github/workflows/ios-build-scripts.yml
.github/workflows/macos-build-scripts.yml
.github/workflows/periodic-builds-apple.yml
.github/workflows/tvos-build-scripts.yml
README.md

update project README
